

==you should only handle errors once.==

思考

+ 为什么标准库中errors.New会返回一个指针？





# Error vs Exception

Go *error* 就是普通的一个接口，普通的值

```go
// The error built-in interface type is the conventional interface for
// representing an error condition, with the nil value representing no error.
type error interface {
	Error() string
}
```

我们经常使用 *errors.New()* 来返回一个 *error* 对象。

```go
// New returns an error that formats as the given text.
// Each call to New returns a distinct error value even if the text is identical.
func New(text string) error {
	return &errorString{text}
}

// errorString is a trivial implementation of error.
type errorString struct {
	s string
}

func (e *errorString) Error() string {
	return e.s
}
```

1. 为什么标准库中errors.New会返回一个指针

我们先来看一个例子，如下：

```go
type myErrorString struct {
	s string
}

func (mError myErrorString) Error() string {
	return mError.s
}

func New(text string) error {
	return myErrorString{text}
}

func main() {
	Error1 := New("error")
	Error2 := New("error")

	if Error1 == Error2 {
		fmt.Printf("%v could not equal %v\n", Error1, Error2)
    // 输出error could not equal error
	}
}
```

这两个`error`有什么问题呢？

如果有两个服务A,B。同时定义了`error:=errors.New("timeout")`。明明是两种不同的错误，但是被当成一种处理。

看看标准库是怎么定义的：

```go
func New(text string) error {
	return &errorString{text}
}
```

在go语言中，在对比两个 struct 是否相同的时候，会去对比，这两个 struct 里面的各个字段是否是相同的，如果相同就返回 true，但是对比指针的时候会去判断两个指针的地址是否一致。

[示例代码](https://github.com/Yefangbiao/study-co/tree/main/Go-training/go-advance/chapter2/error)

2. panic or error

Go 的处理异常逻辑是不引入`exception`，支持多参数返回，所以你很容易的在函数签名中带上实现了 `error interface` 的对象，交由调用者来判定。

如果一个函数返回了 *(value, error)*，你不能对这个 *value* 做任何假设，必须先判定 *error*。唯一可以忽略 *error* 的是，如果你连 *value* 也不关心。

------

Go 中有 panic 的机制，如果你认为和其他语言的 exception 一样，那你就错了。当我们抛出异常的时候，相当于你把 exception 扔给了调用者来处理。

比如，你在 *C++* 中，把 *string* 转为 *int*，如果转换失败，会抛出异常。或者在 *Java* 中转换 *String* 为 *Date* 失败时，会抛出异常。

*Go panic* 意味着 *fatal error*（就是挂了）。不能假设调用者来解决 *panic*，意味着代码不能继续运行。

> 使用多个返回值和一个简单的约定，Go 解决了让程序员知道什么时候出了问题，并为真正的异常情况保留了 panic。

# Error Type

1. Sentinel Error

哨兵错误，就是定义一些包级别的错误变量，然后在调用的时候外部包可以直接对比变量进行判定，在标准库当中大量的使用了这种方式

预定义的特定错误，我们叫为`sentinel error`，这个名字来源于计算机编程中使用一个特定值来表示不可能进行进一步处理的做法。所以对于 Go，我们使用特定的值来表示错误。

比如go `IO` 库提供的错误：

```go
// EOF is the error returned by Read when no more input is available.
// Functions should return EOF only to signal a graceful end of input.
// If the EOF occurs unexpectedly in a structured data stream,
// the appropriate error is either ErrUnexpectedEOF or some other error
// giving more detail.
var EOF = errors.New("EOF")

// ErrUnexpectedEOF means that EOF was encountered in the
// middle of reading a fixed-size block or data structure.
var ErrUnexpectedEOF = errors.New("unexpected EOF")

// ErrNoProgress is returned by some clients of an io.Reader when
// many calls to Read have failed to return any data or error,
// usually the sign of a broken io.Reader implementation.
var ErrNoProgress = errors.New("multiple Read calls return no data or error")
```

我们在外部判定的时候一般使用等值判定或者使用 `errors.Is` 进行判断,直接使用`==`也是可以的。

问题：

+ 这种错误处理方式有一个问题是，将 error 当做包的 API `暴露给了第三方`，这样会导致在做重构或者升级的时候很麻烦，并且这种方式包含的错误信息会十分的有限
+ Sentinel errors 在两个包之间创建了依赖。 *sentinel errors* 最糟糕的问题是它们在两个包之间创建了源代码依赖关系。例如，检查错误是否等于 *io.EOF*，您的代码必须导入 *io* 包。这个特定的例子听起来并不那么糟糕，因为它非常常见，但是想象一下，当项目中的许多包导出错误值时，存在耦合，项目中的其他包必须导入这些错误值才能检查特定的错误条件（*in the form of an import loop*）。
+ 不依赖检查 error.Error 的输出。不应该依赖检测 *error.Error* 的输出，*Error* 方法存在于 *error* 接口主要用于方便程序员使用，但不是程序（编写测试可能会依赖这个返回）。这个输出的字符串用于记录日志、输出到 *stdout* 等。

2. Error Type

Error type 是实现了 `error` 接口的自定义类型。例如 `MyError` 类型记录了文件和行号以展示发生了什么。

```go
type MyError struct {
	Msg  string
	File string
	Line int
}

func (m *MyError) Error() string {
	return fmt.Sprintf("%s:%d: %s", m.File, m.Line, m.Msg)
}
```

因为 `MyError` 是一个 type，调用者可以使用断言转换成这个类型，来获取更多的上下文信息。 

与错误值相比，错误类型的一大改进是它们能够包装底层错误以提供更多上下文。

一个不错的例子就是 `os.PathError` 它提供了底层执行了什么操作、那个路径出了什么问题。

这个就类似我们前面定义的 `errorString` 一样实现了 `error` 的接口，然后在外部是否类型断言来判断是否是这种错误类型

```go
func New() error {
	return &MyError{
		Msg:  "File can not found",
		File: "test.txt",
		Line: 32,
	}
}

func main() {
	err:=New()

	switch err.(type) {
	case *MyError:
		fmt.Println("error:", err)
	}
}
```

这种方式相对于哨兵来说，可以包含更加丰富的信息，但是同样也将错误的类型暴露给了外部

调用者要使用类型断言和类型 `switch`，就要让自定义的 `error` 变为 public。这种模型会导致和调用者产生强耦合，从而导致 API 变得脆弱。

结论是尽量避免使用 error types，虽然错误类型比 sentinel errors 更好，因为它们可以捕获关于出错的更多上下文，但是 error types 共享 error values 许多相同的问题。

因此，我的建议是避免错误类型，或者至少避免将它们作为公共 API 的一部分。

3.  Opaque errors

不透明的错误处理，这种方式最大的特点就是只返回错误，暴露错误判定接口，不返回类型，这样可以减少 API 的暴露，后续的处理会比较灵活，这个一般用在公共库会比较好

```go
func fn()error{
  x,err:=bar.Foo()
  if err!=nil{
    return err
  }
  //...
}
```

在少数情况下，这种二分错误处理方法是不够的。例如，与进程外的世界进行交互（如网络活动），需要调用方调查错误的性质，以确定重试该操作是否合理。在这种情况下，我们可以断言错误实现了特定的行为，而不是断言错误是特定的类型或值。我们来看标准库：

```go
type temporary interface {
	Temporary() bool
}

func IsTemporary(err error) bool {
	te, ok := err.(temporary)
	return ok && te.Temporary()
}
```

这种方式我们可以断言错误实现了特定的行为，而不是断言错误是特定的类型或值

[示例代码](https://github.com/Yefangbiao/study-co/tree/main/Go-training/go-advance/chapter2/errortype)

# Handling Error



# 补充

1. error处理规范

+ 我们在应用程序中使用 `github.com/pkg/errors` 处理应用错误，**注意在公共库当中，我们一般不使用这个**
+ `error` 应该是函数的最后一个返回值，当 `error` 不为 `nil` 时，函数的其他返回值是不可用的状态，不应该对其他返回值做任何期待
+ 在**应用程序**中出现错误时，使用 `errors.New` 或者 `errors.Errorf` 返回错误

```go
func GetErrorf() error {
	return errors.Errorf("errorf error")
}

func GetErrorNew() error {
	return errors.New("new error")
}
```

+ 如果是调用**应用程序的**其他函数出现错误，请直接返回，如果需要携带信息，请使用 `errors.WithMessage`

```go
func ErrorWithMessage() error {
	err := GetErrorNew()
	return errors.WithMessage(err,"message: none")
}
```

+ 如果是调用其他库（标准库、企业公共库、开源第三方库等）获取到错误时，请使用`errors.Wrap`添加堆栈信息
  1. 切记，不要每个地方都是用 `errors.Wrap` 只需要在错误第一次出现时进行 `errors.Wrap` 即可
  2. 根据场景进行判断是否需要将其他库的原始错误吞掉，例如可以把 `repository` 层的数据库相关错误吞掉，返回业务错误码，避免后续我们分割微服务或者更换 `ORM` 库时需要去修改上层代码
  3. 注意我们在基础库，被大量引入的第三方库编写时一般不使用 `errors.Wrap` 避免堆栈信息重复

```go
func ErrorWrap() error {
	_, err := json.Marshal(make(chan int))
	return errors.Wrap(err, "wrap: none")
}
```

+ **禁止**每个出错的地方都打日志，**只需要**在进程的最开始的地方使用 `%+v` 进行统一打印，例如 http/rpc 服务的中间件

```go
fmt.Printf("%+v", ErrorWrap())
```

+ 错误判断使用 `errors.Is` 进行比较

```go
error1 := GetErrorf()
	if errors.Is(error1, io.EOF) {
		fmt.Println(error1)
	}
```

+ 错误类型判断，使用 `errors.As` 进行赋值

```go
error2 := GetErrorNew()
	anotherError := errors.New("another new error")
	if errors.As(error2, &anotherError) {
		fmt.Println(error2)
	}
```

+ 处理错误的时候，需要处理已分配的资源，使用 `defer` 进行清理，例如文件句柄

[示例代码](https://github.com/Yefangbiao/study-co/tree/main/Go-training/go-advance/chapter2/errors)

2. 为什么不允许处处使用`errors.Wrap`

因为每一次 `errors.Wrap` 的调用都会为错误添加堆栈信息，如果处处调用那会有大量的无用堆栈

+ 我们先看一下只有一处 wrap

```go
func main() {
	fmt.Printf("err: %+v", c())
}

func a() error {
	return errors.Wrap(fmt.Errorf("xxx"), "test")
}

func b() error {
	return a()
}

func c() error {
	return b()
}
```

看结果我们可以发现已经可以打印出全部的堆栈信息了

```go
err: xxx
test
main.a
        /home/ll/project/Go-000/Week02/blog/wrap.go:14
main.b
        /home/ll/project/Go-000/Week02/blog/wrap.go:18
main.c
        /home/ll/project/Go-000/Week02/blog/wrap.go:22
main.main
        /home/ll/project/Go-000/Week02/blog/wrap.go:10
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

+ 再看多处 wrap 的现象

```go
func main() {
	fmt.Printf("err: %+v", c())
}

func a() error {
	return errors.Wrap(fmt.Errorf("xxx"), "a")
}

func b() error {
	return errors.Wrap(a(), "b")
}

func c() error {
	return errors.Wrap(b(), "c")
}
```

可以看到每一处 wrap 都添加了一次堆栈信息

```go
err: xxx
a
main.a
        /home/ll/project/Go-000/Week02/blog/wrap.go:14
main.b
        /home/ll/project/Go-000/Week02/blog/wrap.go:18
main.c
        /home/ll/project/Go-000/Week02/blog/wrap.go:22
main.main
        /home/ll/project/Go-000/Week02/blog/wrap.go:10
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
b
main.b
        /home/ll/project/Go-000/Week02/blog/wrap.go:18
main.c
        /home/ll/project/Go-000/Week02/blog/wrap.go:22
main.main
        /home/ll/project/Go-000/Week02/blog/wrap.go:10
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
c
main.c
        /home/ll/project/Go-000/Week02/blog/wrap.go:22
main.main
        /home/ll/project/Go-000/Week02/blog/wrap.go:10
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

3. errors.wrap 有何作用，为什么不用标准库的 `fmt.Errorf("%w")`

我们先看一下标准库的源码，我们可以发现当 `p.wrappedErr != nil` 的时候（也就是有 %w）的时候，会使用一个 `wrapError` 将错误包装，看 `wrapError` 的源码可以发现，这个方法只是包装了一下原始错误，并且可以做到附加一些文本信息，但是没有堆栈信息

